<?php
require_once("./classes/db.class.php");
require_once("./classes/navbar.class.php");

$navbar = new Navbar($dbConn);
?>

<ul class="inner-nav">
    <li class="categories">
        <i class="fa fa-bars" aria-hidden="true"></i>
        <span> Produse </span>
    </li>

    <li>
        <i class="fa fa-info-circle" aria-hidden="true"></i>
        <a href="#">
            <span> ITMAG Help </span>
        </a>
    </li>
</ul>

<section class="inner-nav-header">
    <ul class="inner-nav-header__categories">
        <?php
        $navbar->getProductCategories();
        ?>
    </ul>

    <div class="inner-nav-header__carousel">
        <div class="inner-nav-header__carousel__slider">
            <!-- This Content Would Be Generated By PHP -->
            <div class="inner-nav-header__carousel__slide">
                <a href="#">
                    <img src="assets/imgs/slide-test.jpg" />
                </a>
            </div>
            <div class="inner-nav-header__carousel__slide">
                <a href="#">
                    <img src="assets/imgs/slide-test.jpg" />
                </a>
            </div>

            <div class="inner-nav-header__carousel__slide">
                <a href="#">
                    <img src="assets/imgs/slide-test.jpg" />
                </a>
            </div>

            <div class="inner-nav-header__carousel__slide">
                <a href="#">
                    <img src="assets/imgs/slide-test.jpg" />
                </a>
            </div>

            <div class="inner-nav-header__carousel__slide">
                <a href="#">
                    <img src="assets/imgs/slide-test.jpg" />
                </a>
            </div>
        </div>

        <div class="inner-nav-header__carousel__bullets">
        </div>

        <i class="fa fa-chevron-left" aria-hidden="true"></i>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </div>
</section>

<?php
$dbConn->close();
?>